name: forif
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:

  url_launcher: ^6.2.5
  tflite_flutter: ^0.11.0
  flutter_inappwebview: ^6.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.1.0
  google_fonts: ^6.2.1
  lottie: ^2.2.0
  firebase_core: ^3.6.0
  html: ^0.15.0  # Add this line
  xml: ^6.5.0
  connectivity_plus: ^5.0.2
  flutter_html: ^3.0.0-beta.2
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.2.1
  firebase_database: ^11.1.6
  flutter_tts: ^3.6.0
  webview_flutter: ^4.0.0 # or the latest version
  webview_flutter_android: ^3.16.2
  webview_flutter_wkwebview: ^3.13.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true



  assets:
    - assets/animations/news.json
    - assets/animations/loading.json
    - assets/icons.png
    - assets/geonews.png
    - assets/images/dawnnews.png
    - assets/images/aljazeera.png
    - assets/images/foxnews.png
    - assets/images/googlenews.png
    - assets/images/guardnews.jpg
    - assets/images/cnnnews.png
    - assets/images/bolnews.png
    - assets/images/bbcnews.png
    - assets/images/foxnews.png
    - assets/images/arynews.jpg
    - assets/images/asport.jpg
    - assets/images/skynews.jpg
    - assets/images/expresstribune.jpg
    - assets/images/pktodaynews.jpg
    - assets/images/mashriqnews.jpg
    - assets/images/nytimesnews.png
    - assets/images/humnews.jpg
    - assets/images/gnnnews.jpg
    - assets/images/abtaknews.jpg

